//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class movementsTable
    {
        public int movementsId { get; set; }
        public string plaque { get; set; }
        public string oilType { get; set; }
        public Nullable<int> liter { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
