//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class oilTable
    {
        public int oilId { get; set; }
        public string oilType { get; set; }
        public Nullable<decimal> purchasePrice { get; set; }
        public Nullable<decimal> salePrice { get; set; }
        public Nullable<int> stock { get; set; }
    }
}
